import { Athlete } from './components/Athlete';

export const mockAthletes: Athlete[] = [
    { firstName: 'Ava', lastName: 'Thompson', gender: 'Female', skillRating: 7 },
    { firstName: 'Liam', lastName: 'Garcia', gender: 'Male', skillRating: 4 },
    { firstName: 'Olivia', lastName: 'Martinez', gender: 'Female', skillRating: 9 },
    { firstName: 'Noah', lastName: 'Robinson', gender: 'Male', skillRating: 2 },
    { firstName: 'Emma', lastName: 'Clark', gender: 'Female', skillRating: 6 },
    { firstName: 'Elijah', lastName: 'Rodriguez', gender: 'Male', skillRating: 8 },
    { firstName: 'Charlotte', lastName: 'Lewis', gender: 'Female', skillRating: 3 },
    { firstName: 'James', lastName: 'Walker', gender: 'Male', skillRating: 5 },
    { firstName: 'Amelia', lastName: 'Hall', gender: 'Female', skillRating: 10 },
    { firstName: 'Benjamin', lastName: 'Allen', gender: 'Male', skillRating: 1 },
    { firstName: 'Mia', lastName: 'Young', gender: 'Female', skillRating: 6 },
    { firstName: 'Lucas', lastName: 'Hernandez', gender: 'Male', skillRating: 7 },
    { firstName: 'Harper', lastName: 'King', gender: 'Female', skillRating: 4 },
    { firstName: 'Henry', lastName: 'Wright', gender: 'Male', skillRating: 9 },
    { firstName: 'Evelyn', lastName: 'Lopez', gender: 'Female', skillRating: 2 },
    { firstName: 'Alexander', lastName: 'Hill', gender: 'Male', skillRating: 8 },
    { firstName: 'Abigail', lastName: 'Scott', gender: 'Female', skillRating: 5 },
    { firstName: 'Michael', lastName: 'Green', gender: 'Male', skillRating: 3 },
    { firstName: 'Emily', lastName: 'Adams', gender: 'Female', skillRating: 10 },
    { firstName: 'Daniel', lastName: 'Baker', gender: 'Male', skillRating: 6 },
    { firstName: 'Elizabeth', lastName: 'Nelson', gender: 'Female', skillRating: 1 },
    { firstName: 'Matthew', lastName: 'Carter', gender: 'Male', skillRating: 7 },
    { firstName: 'Sofia', lastName: 'Mitchell', gender: 'Female', skillRating: 4 },
    { firstName: 'Jackson', lastName: 'Perez', gender: 'Male', skillRating: 9 },
    { firstName: 'Avery', lastName: 'Roberts', gender: 'Female', skillRating: 8 },
    { firstName: 'Sebastian', lastName: 'Turner', gender: 'Male', skillRating: 2 },
    { firstName: 'Ella', lastName: 'Phillips', gender: 'Female', skillRating: 5 },
    { firstName: 'Jack', lastName: 'Campbell', gender: 'Male', skillRating: 3 },
    { firstName: 'Scarlett', lastName: 'Parker', gender: 'Female', skillRating: 7 },
    { firstName: 'Owen', lastName: 'Evans', gender: 'Male', skillRating: 10 }
];
